import React from 'react';
import { useTheme } from './ThemeContext';
const Books = () => {
  const { isDarkMode } = useTheme();
  return (
    <>
    <div className={`pt-5 ${isDarkMode ? 'bg-[url("./src/assets/black-chalk.jpg")] text-white' : 'bg-slate-300 text-black'}`}>
      <div className='flex flex-col items-center  bg-cover py-6'>
        <h1 className='text-2xl md:text-3xl  text-center pl-10 pr-10 font-semibold'>Sample Books Generated by BookAI</h1>
        <p className='text-lg md:text-xl text-center mt-2 pl-10 pr-10'>Explore some of the captivating books created using our AI technology.</p>
      </div>
      <div className='flex justify-center py-6'>
        <div className='grid m-20 grid-cols-1 sm:grid-cols-2 md:grid-cols-2 lg:grid-cols-3 gap-6 p-4 max-w-screen-lg'>
          <div className=' transition-transform transform hover:-translate-y-2  p-4 rounded-lg text-center bg-black/40 '>
            <img src='./src/assets/ar.jpg' alt='Book Cover' className='w-3/4 h-auto mx-auto rounded' />
            <h2 className=' text-lg md:text-xl mt-4 font-semibold'>Science Fiction</h2>
            <p className=' mt-2'>"As Dr. Elara stepped through the shimmering portal, she knew there was no turning back. The fate of two universes now rested in her hands..."</p>
            <p className={`${isDarkMode ? 'text-blue-500 mt-4 cursor-pointer hover:text-teal-500' :'text-yellow-300 mt-4 cursor-pointer hover:text-green-400'}`}>Read More</p>
          </div>
          <div className=' transition-transform transform hover:-translate-y-2  p-4 rounded-lg text-center bg-black/40 '>
            <img src='./src/assets/h.webp' alt='Book Cover' className='w-3/4 h-auto mx-auto rounded' />
            <h2 className=' text-lg md:text-xl mt-4 font-semibold'>Mystery</h2>
            <p className=' mt-2'>"The old lighthouse stood silent, its beacon long extinguished. But on foggy nights, some swore they could still see its ghostly light..."</p>
            <p className={`${isDarkMode ? 'text-blue-500 mt-4 cursor-pointer hover:text-teal-500' :'text-yellow-300 mt-4 cursor-pointer hover:text-green-400'}`}>Read More</p>
          </div>
          <div className=' transition-transform transform hover:-translate-y-2  p-4 rounded-lg text-center bg-black/40 '>
            <img src='./src/assets/fan.jpeg' alt='Book Cover' className='w-3/4 h-auto mx-auto rounded' />
            <h2 className=' text-lg md:text-xl mt-4 font-semibold'>Fantasy</h2>
            <p className=' mt-2'>"The ancient prophecy spoke of a child born with starlight in their eyes. As the comet blazed overhead, the kingdom held its breath..."</p>
            <p className={`${isDarkMode ? 'text-blue-500 mt-4 cursor-pointer hover:text-teal-500' :'text-yellow-300 mt-4 cursor-pointer hover:text-green-400'}`}>Read More</p>
          </div>
        </div>
      </div>
      </div>
    </>
  );
}

export default Books;
